FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY backend ./backend
COPY syncserver ./syncserver
COPY cmd ./cmd
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/todo-server ./cmd/todo-server

FROM alpine:3.22
RUN addgroup -S todo && adduser -S -G todo todo && apk add --no-cache ca-certificates tzdata
USER todo
COPY --from=build /out/todo-server /usr/local/bin/todo-server
EXPOSE 8080
ENTRYPOINT ["todo-server"]
