// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AcceptInvitation(arg1:string):Promise<void>;

export function AcquireEditLease(arg1:string,arg2:boolean):Promise<backend.EditLease>;

export function AddNoteAttachments(arg1:string):Promise<Array<backend.Attachment>>;

export function CreateComment(arg1:backend.CommentInput):Promise<backend.Comment>;

export function CreateList(arg1:string):Promise<backend.TodoList>;

export function CreateNote(arg1:backend.CreateNoteInput):Promise<backend.Note>;

export function CreateNoteTag(arg1:backend.NoteTagInput):Promise<backend.NoteTag>;

export function CreateNotebook(arg1:string):Promise<backend.Notebook>;

export function CreateNotebookInvite(arg1:backend.InvitationInput):Promise<backend.InvitationResult>;

export function CreateTag(arg1:backend.TagInput):Promise<backend.Tag>;

export function CreateTask(arg1:backend.CreateTaskInput):Promise<backend.Task>;

export function DeleteAttachment(arg1:string,arg2:string):Promise<void>;

export function DeleteComment(arg1:string):Promise<void>;

export function DeleteList(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteNoteTag(arg1:string):Promise<void>;

export function DeleteNotebook(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function ExportBackup():Promise<backend.FileResult>;

export function GetBootstrap():Promise<backend.Bootstrap>;

export function GetCompactMode():Promise<boolean>;

export function GetNote(arg1:string):Promise<backend.Note>;

export function GetOverview():Promise<backend.Overview>;

export function GetSyncStatus():Promise<backend.SyncStatus>;

export function ImportBackup():Promise<backend.ImportResult>;

export function ListComments(arg1:string):Promise<Array<backend.Comment>>;

export function ListNoteTags(arg1:string):Promise<Array<backend.NoteTag>>;

export function ListNoteVersions(arg1:string):Promise<Array<backend.NoteVersion>>;

export function ListNotebookMembers(arg1:string):Promise<Array<backend.NotebookMember>>;

export function ListNotebooks():Promise<Array<backend.Notebook>>;

export function ListNotes(arg1:backend.NoteQuery):Promise<Array<backend.NoteSummary>>;

export function ListNotifications():Promise<Array<backend.Notification>>;

export function ListTasks(arg1:backend.TaskQuery):Promise<Array<backend.Task>>;

export function Login(arg1:backend.LoginInput):Promise<backend.LoginResult>;

export function Logout():Promise<void>;

export function MarkNotificationRead(arg1:string):Promise<void>;

export function OpenAttachment(arg1:string):Promise<void>;

export function ReadAttachment(arg1:string):Promise<backend.AttachmentContent>;

export function ReleaseEditLease(arg1:string):Promise<void>;

export function RemoveNotebookMember(arg1:string,arg2:string):Promise<void>;

export function RestoreNote(arg1:string):Promise<backend.Note>;

export function RestoreNoteVersion(arg1:string):Promise<backend.Note>;

export function RestoreTask(arg1:string):Promise<backend.Task>;

export function SavePastedAttachment(arg1:backend.AttachmentUploadInput):Promise<backend.Attachment>;

export function SetCompactMode(arg1:boolean):Promise<void>;

export function SetNotePinned(arg1:string,arg2:boolean):Promise<backend.Note>;

export function SetTaskCompleted(arg1:string,arg2:boolean):Promise<backend.Task>;

export function SyncNow():Promise<backend.SyncStatus>;

export function TransferNotebookOwnership(arg1:string,arg2:string):Promise<void>;

export function UpdateComment(arg1:backend.CommentInput):Promise<backend.Comment>;

export function UpdateList(arg1:backend.ListInput):Promise<backend.TodoList>;

export function UpdateNote(arg1:backend.UpdateNoteInput):Promise<backend.Note>;

export function UpdateNoteTag(arg1:backend.NoteTagInput):Promise<backend.NoteTag>;

export function UpdateNotebook(arg1:backend.NotebookInput):Promise<backend.Notebook>;

export function UpdateNotebookMember(arg1:backend.MemberUpdateInput):Promise<void>;

export function UpdateSettings(arg1:backend.AppSettings):Promise<backend.AppSettings>;

export function UpdateTag(arg1:backend.TagInput):Promise<backend.Tag>;

export function UpdateTask(arg1:backend.UpdateTaskInput):Promise<backend.Task>;
