// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptInvitation(arg1) {
  return window['go']['backend']['App']['AcceptInvitation'](arg1);
}

export function AcquireEditLease(arg1, arg2) {
  return window['go']['backend']['App']['AcquireEditLease'](arg1, arg2);
}

export function AddNoteAttachments(arg1) {
  return window['go']['backend']['App']['AddNoteAttachments'](arg1);
}

export function CreateComment(arg1) {
  return window['go']['backend']['App']['CreateComment'](arg1);
}

export function CreateList(arg1) {
  return window['go']['backend']['App']['CreateList'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['backend']['App']['CreateNote'](arg1);
}

export function CreateNoteTag(arg1) {
  return window['go']['backend']['App']['CreateNoteTag'](arg1);
}

export function CreateNotebook(arg1) {
  return window['go']['backend']['App']['CreateNotebook'](arg1);
}

export function CreateNotebookInvite(arg1) {
  return window['go']['backend']['App']['CreateNotebookInvite'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['backend']['App']['CreateTag'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['backend']['App']['CreateTask'](arg1);
}

export function DeleteAttachment(arg1, arg2) {
  return window['go']['backend']['App']['DeleteAttachment'](arg1, arg2);
}

export function DeleteComment(arg1) {
  return window['go']['backend']['App']['DeleteComment'](arg1);
}

export function DeleteList(arg1) {
  return window['go']['backend']['App']['DeleteList'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['backend']['App']['DeleteNote'](arg1);
}

export function DeleteNoteTag(arg1) {
  return window['go']['backend']['App']['DeleteNoteTag'](arg1);
}

export function DeleteNotebook(arg1) {
  return window['go']['backend']['App']['DeleteNotebook'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['backend']['App']['DeleteTag'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['backend']['App']['DeleteTask'](arg1);
}

export function ExportBackup() {
  return window['go']['backend']['App']['ExportBackup']();
}

export function GetBootstrap() {
  return window['go']['backend']['App']['GetBootstrap']();
}

export function GetCompactMode() {
  return window['go']['backend']['App']['GetCompactMode']();
}

export function GetNote(arg1) {
  return window['go']['backend']['App']['GetNote'](arg1);
}

export function GetOverview() {
  return window['go']['backend']['App']['GetOverview']();
}

export function GetSyncStatus() {
  return window['go']['backend']['App']['GetSyncStatus']();
}

export function ImportBackup() {
  return window['go']['backend']['App']['ImportBackup']();
}

export function ListComments(arg1) {
  return window['go']['backend']['App']['ListComments'](arg1);
}

export function ListNoteTags(arg1) {
  return window['go']['backend']['App']['ListNoteTags'](arg1);
}

export function ListNoteVersions(arg1) {
  return window['go']['backend']['App']['ListNoteVersions'](arg1);
}

export function ListNotebookMembers(arg1) {
  return window['go']['backend']['App']['ListNotebookMembers'](arg1);
}

export function ListNotebooks() {
  return window['go']['backend']['App']['ListNotebooks']();
}

export function ListNotes(arg1) {
  return window['go']['backend']['App']['ListNotes'](arg1);
}

export function ListNotifications() {
  return window['go']['backend']['App']['ListNotifications']();
}

export function ListTasks(arg1) {
  return window['go']['backend']['App']['ListTasks'](arg1);
}

export function Login(arg1) {
  return window['go']['backend']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['backend']['App']['Logout']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['backend']['App']['MarkNotificationRead'](arg1);
}

export function OpenAttachment(arg1) {
  return window['go']['backend']['App']['OpenAttachment'](arg1);
}

export function ReadAttachment(arg1) {
  return window['go']['backend']['App']['ReadAttachment'](arg1);
}

export function ReleaseEditLease(arg1) {
  return window['go']['backend']['App']['ReleaseEditLease'](arg1);
}

export function RemoveNotebookMember(arg1, arg2) {
  return window['go']['backend']['App']['RemoveNotebookMember'](arg1, arg2);
}

export function RestoreNote(arg1) {
  return window['go']['backend']['App']['RestoreNote'](arg1);
}

export function RestoreNoteVersion(arg1) {
  return window['go']['backend']['App']['RestoreNoteVersion'](arg1);
}

export function RestoreTask(arg1) {
  return window['go']['backend']['App']['RestoreTask'](arg1);
}

export function SavePastedAttachment(arg1) {
  return window['go']['backend']['App']['SavePastedAttachment'](arg1);
}

export function SetCompactMode(arg1) {
  return window['go']['backend']['App']['SetCompactMode'](arg1);
}

export function SetNotePinned(arg1, arg2) {
  return window['go']['backend']['App']['SetNotePinned'](arg1, arg2);
}

export function SetTaskCompleted(arg1, arg2) {
  return window['go']['backend']['App']['SetTaskCompleted'](arg1, arg2);
}

export function SyncNow() {
  return window['go']['backend']['App']['SyncNow']();
}

export function TransferNotebookOwnership(arg1, arg2) {
  return window['go']['backend']['App']['TransferNotebookOwnership'](arg1, arg2);
}

export function UpdateComment(arg1) {
  return window['go']['backend']['App']['UpdateComment'](arg1);
}

export function UpdateList(arg1) {
  return window['go']['backend']['App']['UpdateList'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['backend']['App']['UpdateNote'](arg1);
}

export function UpdateNoteTag(arg1) {
  return window['go']['backend']['App']['UpdateNoteTag'](arg1);
}

export function UpdateNotebook(arg1) {
  return window['go']['backend']['App']['UpdateNotebook'](arg1);
}

export function UpdateNotebookMember(arg1) {
  return window['go']['backend']['App']['UpdateNotebookMember'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['backend']['App']['UpdateSettings'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['backend']['App']['UpdateTag'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['backend']['App']['UpdateTask'](arg1);
}
