import {expect, test} from '@playwright/test'

test.beforeEach(async ({page}) => {
    await page.goto('/')
    await page.evaluate(() => localStorage.clear())
    await page.reload()
})

test('desktop task workflow and light theme screenshot', async ({page}) => {
    await page.setViewportSize({width: 1200, height: 780})
    const quickAdd = page.getByLabel('添加任务')
    await quickAdd.fill('准备周一项目同步')
    await quickAdd.press('Enter')
    await expect(page.getByText('准备周一项目同步').first()).toBeVisible()
    await expect(page.getByRole('button', {name: /全部任务/}).locator('.sidebar-count')).toHaveText('1')
    const alignment = await page.locator('.task-row').first().evaluate((row) => {
        const checkbox = row.querySelector('.complete-button')!.getBoundingClientRect()
        const title = row.querySelector('.task-title')!.getBoundingClientRect()
        return Math.abs((checkbox.top + checkbox.height / 2) - (title.top + title.height / 2))
    })
    expect(alignment).toBeLessThanOrEqual(1)
    await page.getByLabel('任务标题').fill('准备周一项目同步会议')
    await page.getByLabel('备注').fill('整理进度、风险和接下来的安排。')
    await page.getByRole('button', {name: '高'}).click()
    await page.getByRole('button', {name: '保存更改'}).click()
    const toast = page.getByRole('status')
    await expect(toast.getByText('更改已保存')).toBeVisible()
    await expect(toast).not.toContainText('error parsing arguments')
    const toastBox = await toast.boundingBox()
    expect(toastBox).not.toBeNull()
    expect(toastBox!.y).toBeLessThan(90)
    expect(Math.abs(toastBox!.x + toastBox!.width / 2 - 600)).toBeLessThanOrEqual(2)
    expect(await page.locator('select').count()).toBe(0)
    const priorityFilter = page.getByRole('combobox', {name: '优先级'})
    expect(await priorityFilter.evaluate((element) => element.tagName)).toBe('BUTTON')
    await priorityFilter.click()
    await expect(page.getByRole('option', {name: '高优先级'})).toBeVisible()
    await expect(page.locator('.select-content')).toHaveScreenshot('todo-priority-select.png', {animations: 'disabled'})
    await page.getByRole('option', {name: '全部优先级'}).click()
    await expect(page.locator('body')).toHaveScreenshot('todo-desktop-light.png', {animations: 'disabled'})

    await page.locator('.task-row').first().click({button: 'right'})
    await expect(page.getByRole('menuitem', {name: '打开详情'})).toBeVisible()
    await expect(page.locator('.task-context-menu')).toHaveScreenshot('todo-task-context-menu.png', {animations: 'disabled'})
    await page.keyboard.press('Escape')

    await page.getByRole('button', {name: '新建标签'}).click()
    await page.getByLabel('名称').fill('work')
    await page.getByRole('button', {name: '保存'}).click()
    await expect(page.locator('.tags-section')).toContainText('work')
    const listSection = page.locator('.sidebar .sidebar-section').first()
    const workListRow = listSection.locator('.entity-row').filter({hasText: '工作'})
    const personalListRow = listSection.locator('.entity-row').filter({hasText: '个人'})
    const workTagRow = page.locator('.tags-section .entity-row').filter({hasText: 'work'})
    await expect(workListRow.locator('.sidebar-count')).toHaveCount(0)
    await expect(personalListRow.locator('.sidebar-count')).toHaveCount(0)
    await expect(workTagRow.locator('.sidebar-count')).toHaveCount(0)
    await page.getByRole('button', {name: '全部任务'}).click()
    const taskRow = page.locator('.task-row').first()
    await taskRow.click()

    const openTaskMenu = async () => {
        await taskRow.click({button: 'right'})
        await expect(page.locator('.task-context-menu')).toBeVisible()
    }

    await openTaskMenu()
    await page.getByRole('menuitem', {name: '清单'}).hover()
    await page.getByRole('menuitemradio', {name: '工作'}).click()
    await expect(page.getByRole('combobox', {name: '清单'})).toContainText('工作')
    await expect(workListRow.locator('.sidebar-count')).toHaveText('1')
    await expect(personalListRow.locator('.sidebar-count')).toHaveCount(0)

    await openTaskMenu()
    await page.getByRole('menuitem', {name: '优先级'}).hover()
    await expect(page.locator('.menu-sub-content')).toHaveScreenshot('todo-task-priority-submenu.png', {animations: 'disabled', maxDiffPixels: 12})
    await page.getByRole('menuitemradio', {name: '低优先级'}).click()
    await expect(page.getByRole('button', {name: '低'})).toHaveClass(/is-active/)

    await openTaskMenu()
    await page.getByRole('menuitem', {name: '截止日期'}).hover()
    await page.getByRole('menuitemradio', {name: '明天'}).click()
    await expect(taskRow).toContainText('明天')

    await openTaskMenu()
    await page.getByRole('menuitem', {name: '标签'}).hover()
    await page.getByRole('menuitemcheckbox', {name: 'work'}).click()
    await expect(page.locator('.tag-option').filter({hasText: 'work'})).toHaveAttribute('aria-pressed', 'true')
    await expect(workTagRow.locator('.sidebar-count')).toHaveText('1')
    await expect(page.locator('.sidebar')).toHaveScreenshot('todo-sidebar-counts.png', {animations: 'disabled'})

    await openTaskMenu()
    await page.getByRole('menuitem', {name: '截止日期'}).hover()
    await page.getByRole('menuitem', {name: '选择其他日期'}).click()
    await expect(page.locator('.calendar-popover')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('complementary', {name: '任务详情'})).toBeVisible()

    await openTaskMenu()
    await page.getByRole('menuitem', {name: '删除任务'}).click()
    await expect(page.getByRole('heading', {name: '删除这个任务？'})).toBeVisible()
    await page.getByRole('button', {name: '删除任务'}).click()
    await expect(page.getByText('任务已删除')).toBeVisible()
})

test('narrow layout opens detail as an overlay without overflow', async ({page}) => {
    await page.setViewportSize({width: 900, height: 620})
    const quickAdd = page.getByLabel('添加任务')
    await quickAdd.fill('检查窄窗口布局')
    await quickAdd.press('Enter')
    await expect(page.getByRole('complementary', {name: '任务详情'})).toBeVisible()
    const metrics = await page.evaluate(() => ({
        width: document.documentElement.scrollWidth,
        viewport: document.documentElement.clientWidth,
        height: document.documentElement.scrollHeight,
        viewportHeight: document.documentElement.clientHeight,
    }))
    expect(metrics.width).toBe(metrics.viewport)
    expect(metrics.height).toBe(metrics.viewportHeight)
    await expect(page.locator('body')).toHaveScreenshot('todo-narrow-detail.png', {animations: 'disabled'})
})

test('dark theme remains legible', async ({page}) => {
    await page.setViewportSize({width: 1200, height: 780})
    await page.getByRole('button', {name: '设置与备份'}).click()
    await expect(page.getByRole('button', {name: '跟随系统'})).toBeFocused()
    await page.waitForTimeout(600)
    await expect(page.locator('.tooltip')).toHaveCount(0)
    await page.getByRole('button', {name: '深色'}).click()
    await page.getByRole('button', {name: '保存设置'}).click()
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    await expect(page.locator('body')).toHaveScreenshot('todo-desktop-dark.png', {animations: 'disabled'})
})

test('compact window switches task views without overflow', async ({page}) => {
	await page.setViewportSize({width: 380, height: 540})
	await page.getByRole('button', {name: '悬浮小窗'}).click()
	await expect(page.getByRole('main', {name: '悬浮任务小窗'})).toBeVisible()
	await page.getByLabel('添加今日任务').fill('确认今日发布内容')
	await page.getByLabel('添加今日任务').press('Enter')
	await expect(page.getByText('确认今日发布内容')).toBeVisible()
	await expect(page.getByLabel('窗口已置顶')).toBeVisible()
	const metrics = await page.evaluate(() => ({
		width: document.documentElement.scrollWidth,
		viewport: document.documentElement.clientWidth,
		height: document.documentElement.scrollHeight,
		viewportHeight: document.documentElement.clientHeight,
	}))
	expect(metrics.width).toBe(metrics.viewport)
	expect(metrics.height).toBe(metrics.viewportHeight)
	await expect(page.locator('body')).toHaveScreenshot('todo-compact-window.png', {animations: 'disabled'})
	const viewTrigger = page.getByRole('button', {name: '切换小窗视图，当前今天'})
	await viewTrigger.click()
	await expect(page.getByRole('menuitem', {name: '全部任务'})).toBeVisible()
	await expect(page.locator('.compact-view-menu')).toHaveScreenshot('todo-compact-view-menu.png', {animations: 'disabled'})
	await page.getByRole('menuitem', {name: '全部任务'}).click()
	await expect(page.getByRole('heading', {name: '全部任务'})).toBeVisible()
	await page.getByRole('button', {name: '切换小窗视图，当前全部任务'}).click()
	await page.getByRole('menuitem', {name: '今天'}).click()
	await page.locator('html').evaluate((element) => {element.dataset.theme = 'dark'})
	await expect(page.locator('body')).toHaveScreenshot('todo-compact-window-dark.png', {animations: 'disabled'})
	await page.emulateMedia({reducedMotion: 'reduce'})
	await page.getByLabel('标记为已完成').click()
	await expect(page.getByText('今天已经清空了')).toBeVisible()
})

test('notes autosave, preview and remain usable in wide and narrow layouts', async ({page}) => {
    await page.setViewportSize({width: 1200, height: 780})
    await page.getByRole('button', {name: /笔记/}).click()
    await page.locator('[data-new-note]').click()
    await expect(page.getByRole('region', {name: '笔记编辑器'})).toBeVisible()
    await page.getByLabel('笔记标题').fill('离线协作方案')
    await page.getByLabel('笔记正文').fill('# 同步策略\n\n所有更改先保存到本地，再进入同步队列。')
    await expect(page.getByText('有未保存更改')).toBeVisible()
    await expect(page.getByText('已保存')).toBeVisible({timeout: 5_000})
    await page.getByRole('button', {name: '预览'}).click()
    await expect(page.getByRole('heading', {name: '同步策略'})).toBeVisible()
    const wideMetrics = await page.evaluate(() => ({width: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth, height: document.documentElement.scrollHeight, viewportHeight: document.documentElement.clientHeight}))
    expect(wideMetrics.width).toBe(wideMetrics.viewport)
    expect(wideMetrics.height).toBe(wideMetrics.viewportHeight)
    await expect(page.locator('body')).toHaveScreenshot('todo-notes-desktop-light.png', {animations: 'disabled'})

    await page.setViewportSize({width: 900, height: 620})
    await expect(page.getByRole('region', {name: '笔记编辑器'})).toBeVisible()
    const narrowMetrics = await page.evaluate(() => ({width: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth, height: document.documentElement.scrollHeight, viewportHeight: document.documentElement.clientHeight}))
    expect(narrowMetrics.width).toBe(narrowMetrics.viewport)
    expect(narrowMetrics.height).toBe(narrowMetrics.viewportHeight)
    await expect(page.locator('body')).toHaveScreenshot('todo-notes-narrow.png', {animations: 'disabled'})
})
